package cn.a114;

import java.util.Arrays;

public class Main {// OK
    public static void main(String[] args) {
        String[] veryLong = new String[]{"Lorem"
                ,
                "ipsum"
                ,
                "dolor"
                ,
                "sit"
                ,
                "amet,"
                ,
                "consectetur"
                ,
                "adipiscing"
                ,
                "elit."
                ,
                "Sed"
                ,
                "euismod,"
                ,
                "lectus"
                ,
                "in"
                ,
                "luctus"
                ,
                "viverra,"
                ,
                "lacus"
                ,
                "justo"
                ,
                "pulvinar"
                ,
                "dolor,"
                ,
                "nec"
                ,
                "malesuada"
                ,
                "sapien"
                ,
                "justo"
                ,
                "ac"
                ,
                "erat."
                ,
                "Proin"
                ,
                "vel"
                ,
                "pretium"
                ,
                "velit."
                ,
                "Curabitur"
                ,
                "fringilla,"
                ,
                "ipsum"
                ,
                "eu"
                ,
                "eleifend"
                ,
                "pulvinar,"
                ,
                "nulla"
                ,
                "dui"
                ,
                "suscipit"
                ,
                "lorem,"
                ,
                "sed"
                ,
                "sodales"
                ,
                "elit"
                ,
                "est"
                ,
                "ut"
                ,
                "massa."
                ,
                "Nulla"
                ,
                "facilisi."
                ,
                "Integer"
                ,
                "efficitur"
                ,
                "turpis"
                ,
                "in"
                ,
                "lorem"
                ,
                "vehicula,"
                ,
                "a"
                ,
                "tincidunt"
                ,
                "libero"
                ,
                "facilisis."
                ,
                "Nam"
                ,
                "vestibulum,"
                ,
                "turpis"
                ,
                "nec"
                ,
                "porta"
                ,
                "lacinia,"
                ,
                "lorem"
                ,
                "ipsum"
                ,
                "sollicitudin"
                ,
                "justo,"
                ,
                "vitae"
                ,
                "tincidunt"
                ,
                "velit"
                ,
                "eros"
                ,
                "vitae"
                ,
                "ligula."
                ,
                "Maecenas"
                ,
                "luctus"
                ,
                "feugiat"
                ,
                "lacus,"
                ,
                "sed"
                ,
                "porta"
                ,
                "ante"
                ,
                "placerat"
                ,
                "sed."
                ,
                "Sed"
                ,
                "vitae"
                ,
                "lectus"
                ,
                "neque."
                ,
                "Pellentesque"
                ,
                "vulputate,"
                ,
                "purus"
                ,
                "non"
                ,
                "mattis"
                ,
                "eleifend,"
                ,
                "neque"
                ,
                "orci"
                ,
                "malesuada"
                ,
                "erat,"
                ,
                "nec"
                ,
                "luctus"
                ,
                "purus"
                ,
                "enim"
                ,
                "sit"
                ,
                "amet"
                ,
                "elit."
                ,
                "Nulla"
                ,
                "pretium"
                ,
                "risus"
                ,
                "et"
                ,
                "turpis"
                ,
                "commodo,"
                ,
                "id"
                ,
                "auctor"
                ,
                "magna"
                ,
                "dictum."
                ,
                "Curabitur"
                ,
                "ac"
                ,
                "justo"
                ,
                "eget"
                ,
                "elit"
                ,
                "malesuada"
                ,
                "blandit."
                ,
                "Pellentesque"
                ,
                "venenatis"
                ,
                "erat"
                ,
                "sed"
                ,
                "tortor"
                ,
                "bibendum,"
                ,
                "a"
                ,
                "tempor"
                ,
                "nulla"
                ,
                "blandit."
                ,
                "Etiam"
                ,
                "varius"
                ,
                "dapibus"
                ,
                "dictum."
                ,
                "Suspendisse"
                ,
                "quis"
                ,
                "libero"
                ,
                "sed"
                ,
                "erat"
                ,
                "aliquet"
                ,
                "porta"
                ,
                "a"
                ,
                "a"
                ,
                "metus."
                ,
                "Donec"
                ,
                "eget"
                ,
                "mi"
                ,
                "non"
                ,
                "quam"
                ,
                "euismod"
                ,
                "congue."
                ,
                "Curabitur"
                ,
                "feugiat,"
                ,
                "metus"
                ,
                "non"
                ,
                "condimentum"
                ,
                "facilisis,"
                ,
                "ligula"
                ,
                "mi"
                ,
                "ultricies"
                ,
                "ligula,"
                ,
                "vitae"
                ,
                "suscipit"
                ,
                "arcu"
                ,
                "nisi"
                ,
                "sed"
                ,
                "est."
                ,
                "Integer"
                ,
                "pulvinar"
                ,
                "velit"
                ,
                "at"
                ,
                "diam"
                ,
                "vehicula,"
                ,
                "ac"
                ,
                "viverra"
                ,
                "nunc"
                ,
                "facilisis."
                ,
                "Duis"
                ,
                "dictum,"
                ,
                "libero"
                ,
                "sit"
                ,
                "amet"
                ,
                "ultricies"
                ,
                "hendrerit,"
                ,
                "nunc"
                ,
                "urna"
                ,
                "laoreet"
                ,
                "velit,"
                ,
                "id"
                ,
                "sodales"
                ,
                "dolor"
                ,
                "justo"
                ,
                "vitae"
                ,
                "libero."
                ,
                "Sed"
                ,
                "quis"
                ,
                "convallis"
                ,
                "tortor."
                ,
                "Aenean"
                ,
                "varius"
                ,
                "luctus"
                ,
                "nunc,"
                ,
                "vel"
                ,
                "lacinia"
                ,
                "neque"
                ,
                "consectetur"
                ,
                "nec."
                ,
                "Morbi"
                ,
                "non"
                ,
                "luctus"
                ,
                "libero."
                ,
                "Suspendisse"
                ,
                "eget"
                ,
                "bibendum"
                ,
                "arcu,"
                ,
                "non"
                ,
                "accumsan"
                ,
                "odio."
                ,
                "Proin"
                ,
                "viverra"
                ,
                "felis"
                ,
                "non"
                ,
                "sapien"
                ,
                "tincidunt,"
                ,
                "sit"
                ,
                "amet"
                ,
                "vestibulum"
                ,
                "purus"
                ,
                "tristique."
                ,
                "Nulla"
                ,
                "vitae"
                ,
                "risus"
                ,
                "in"
                ,
                "nulla"
                ,
                "fermentum"
                ,
                "aliquam"
                ,
                "a"
                ,
                "sed"
                ,
                "turpis."
                ,
                "Integer"
                ,
                "vitae"
                ,
                "nibh"
                ,
                "bibendum,"
                ,
                "tincidunt"
                ,
                "velit"
                ,
                "nec,"
                ,
                "egestas"
                ,
                "risus."
                ,
                "Ut"
                ,
                "sed"
                ,
                "bibendum"
                ,
                "leo."
                ,
                "Donec"
                ,
                "sagittis"
                ,
                "orci"
                ,
                "ut"
                ,
                "tincidunt"
                ,
                "malesuada."
                ,
                "Sed"
                ,
                "tristique"
                ,
                "dui"
                ,
                "a"
                ,
                "orci"
                ,
                "sodales"
                ,
                "bibendum."
                ,
                "Pellentesque"
                ,
                "ut"
                ,
                "ex"
                ,
                "nec"
                ,
                "sem"
                ,
                "ultricies"
                ,
                "posuere."
                ,
                "Mauris"
                ,
                "maximus"
                ,
                "tellus"
                ,
                "vitae"
                ,
                "dignissim"
                ,
                "fringilla."
                ,
                "Ut"
                ,
                "vel"
                ,
                "augue"
                ,
                "at"
                ,
                "libero"
                ,
                "malesuada"
                ,
                "dignissim"
                ,
                "non"
                ,
                "a"
                ,
                "urna."
                ,
                "Fusce"
                ,
                "aliquet"
                ,
                "nulla"
                ,
                "sed"
                ,
                "neque"
                ,
                "gravida,"
                ,
                "eget"
                ,
                "luctus"
                ,
                "felis"
                ,
                "euismod."
                ,
                "Duis"
                ,
                "vehicula"
                ,
                "mi"
                ,
                "at"
                ,
                "mauris"
                ,
                "ornare"
                ,
                "viverra."
                ,
                "Nunc"
                ,
                "a"
                ,
                "risus"
                ,
                "nec"
                ,
                "ligula"
                ,
                "malesuada"
                ,
                "euismod."
                ,
                "Maecenas"
                ,
                "malesuada"
                ,
                "ex"
                ,
                "eget"
                ,
                "dolor"
                ,
                "pharetra"
                ,
                "volutpat."
                ,
                "Integer"
                ,
                "fermentum"
                ,
                "sapien"
                ,
                "eget"
                ,
                "varius"
                ,
                "euismod."
                ,
                "Nulla"
                ,
                "dapibus"
                ,
                "luctus"
                ,
                "augue"
                ,
                "sit"
                ,
                "amet"
                ,
                "faucibus."
                ,
                "Aenean"
                ,
                "vitae"
                ,
                "imperdiet"
                ,
                "lacus."
                ,
                "Pellentesque"
                ,
                "feugiat"
                ,
                "velit"
                ,
                "vel"
                ,
                "mi"
                ,
                "aliquet"
                ,
                "tincidunt."
                ,
                "Curabitur"
                ,
                "in"
                ,
                "augue"
                ,
                "nisi."
                ,
                "Duis"
                ,
                "maximus"
                ,
                "egestas"
                ,
                "mauris,"
                ,
                "eget"
                ,
                "egestas"
                ,
                "erat"
                ,
                "mattis"
                ,
                "id."
                ,
                "Suspendisse"
                ,
                "eget"
                ,
                "mi"
                ,
                "nec"
                ,
                "magna"
                ,
                "facilisis"
                ,
                "sodales."
                ,
                "Donec"
                ,
                "scelerisque"
                ,
                "magna"
                ,
                "sed"
                ,
                "lorem"
                ,
                "tincidunt,"
                ,
                "eu"
                ,
                "tincidunt"
                ,
                "ligula"
                ,
                "consequat."
                ,
                "Aliquam"
                ,
                "erat"
                ,
                "volutpat."
                ,
                "Vestibulum"
                ,
                "sit"
                ,
                "amet"
                ,
                "libero"
                ,
                "fermentum,"
                ,
                "pretium"
                ,
                "lorem"
                ,
                "sed,"
                ,
                "tempor"
                ,
                "nisi."
                ,
                "Integer"
                ,
                "cursus,"
                ,
                "sapien"
                ,
                "nec"
                ,
                "tempus"
                ,
                "efficitur,"
                ,
                "sapien"
                ,
                "orci"
                ,
                "malesuada"
                ,
                "augue,"
                ,
                "nec"
                ,
                "euismod"
                ,
                "sem"
                ,
                "erat"
                ,
                "ac"
                ,
                "velit."
                ,
                "Suspendisse"
                ,
                "viverra"
                ,
                "malesuada"
                ,
                "turpis,"
                ,
                "a"
                ,
                "sagittis"
                ,
                "nisl"
                ,
                "varius"
                ,
                "id."
                ,
                "Pellentesque"
                ,
                "porttitor"
                ,
                "pretium"
                ,
                "dui"
                ,
                "in"
                ,
                "convallis."
                ,
                "Cras"
                ,
                "dictum"
                ,
                "lorem"
                ,
                "sit"
                ,
                "amet"
                ,
                "risus"
                ,
                "gravida,"
                ,
                "a"
                ,
                "fermentum"
                ,
                "metus"
                ,
                "volutpat."
                ,
                "Integer"
                ,
                "venenatis"
                ,
                "ante"
                ,
                "in"
                ,
                "ex"
                ,
                "volutpat,"
                ,
                "vel"
                ,
                "euismod"
                ,
                "turpis"
                ,
                "bibendum."
                ,
                "Nullam"
                ,
                "vel"
                ,
                "mauris"
                ,
                "et"
                ,
                "ante"
                ,
                "vestibulum"
                ,
                "pulvinar."
                ,
                "Suspendisse"
                ,
                "eu"
                ,
                "turpis"
                ,
                "ac"
                ,
                "libero"
                ,
                "sagittis"
                ,
                "dignissim."
                ,
                "Sed"
                ,
                "vel"
                ,
                "ullamcorper"
                ,
                "purus,"
                ,
                "sed"
                ,
                "malesuada"
                ,
                "risus."
                ,
                "Pellentesque"
                ,
                "nec"
                ,
                "lorem"
                ,
                "id"
                ,
                "odio"
                ,
                "bibendum"
                ,
                "tristique."
                ,
                "Donec"
                ,
                "non"
                ,
                "semper"
                ,
                "ex."
                ,
                "Duis"
                ,
                "sed"
                ,
                "luctus"
                ,
                "dolor."
                ,
                "In"
                ,
                "imperdiet,"
                ,
                "odio"
                ,
                "a"
                ,
                "pulvinar"
                ,
                "vulputate,"
                ,
                "magna"
                ,
                "lacus"
                ,
                "posuere"
                ,
                "justo,"
                ,
                "sed"
                ,
                "suscipit"
                ,
                "arcu"
                ,
                "mi"
                ,
                "eget"
                ,
                "arcu."
                ,
                "Aliquam"
                ,
                "sagittis"
                ,
                "euismod"
                ,
                "justo,"
                ,
                "a"
                ,
                "porta"
                ,
                "dolor"
                ,
                "porttitor"
                ,
                "non."
                ,
                "Cras"
                ,
                "vitae"
                ,
                "dolor"
                ,
                "libero."
                ,
                "Integer"
                ,
                "porta"
                ,
                "imperdiet"
                ,
                "felis,"
                ,
                "a"
                ,
                "tincidunt"
                ,
                "ipsum"
                ,
                "dapibus"
                ,
                "a."
                ,
                "Nullam"
                ,
                "facilisis"
                ,
                "interdum"
                ,
                "ligula,"
                ,
                "nec"
                ,
                "ultricies"
                ,
                "purus"
                ,
                "luctus"
                ,
                "id."
                ,
                "Vestibulum"
                ,
                "ante"
                ,
                "ipsum"
                ,
                "primis"
                ,
                "in"
                ,
                "faucibus"
                ,
                "orci"
                ,
                "luctus"
                ,
                "et"
                ,
                "ultrices"
                ,
                "posuere"
                ,
                "cubilia"
                ,
                "curae;"
                ,
                "Sed"
                ,
                "venenatis,"
                ,
                "purus"
                ,
                "in"
                ,
                "luctus"
                ,
                "tincidunt,"
                ,
                "lectus"
                ,
                "arcu"
                ,
                "tincidunt"
                ,
                "urna,"
                ,
                "at"
                ,
                "scelerisque"
                ,
                "nulla"
                ,
                "ipsum"
                ,
                "eget"
                ,
                "leo."
                ,
                "Sed"
                ,
                "lacinia"
                ,
                "sapien"
                ,
                "sed"
                ,
                "magna"
                ,
                "feugiat,"
                ,
                "nec"
                ,
                "fermentum"
                ,
                "lectus"
                ,
                "ultrices."
                ,
                "Cras"
                ,
                "malesuada"
                ,
                "ipsum"
                ,
                "vel"
                ,
                "purus"
                ,
                "imperdiet,"
                ,
                "vitae"
                ,
                "tincidunt"
                ,
                "justo"
                ,
                "feugiat."
                ,
                "Maecenas"
                ,
                "vitae"
                ,
                "eros"
                ,
                "quam."
                ,
                "In"
                ,
                "at"
                ,
                "orci"
                ,
                "nunc."
                ,
                "Nullam"
                ,
                "eget"
                ,
                "pretium"
                ,
                "sapien."
                ,
                "Suspendisse"
                ,
                "sed"
                ,
                "purus"
                ,
                "a"
                ,
                "ante"
                ,
                "vehicula"
                ,
                "tristique"
                ,
                "nec"
                ,
                "ut"
                ,
                "felis."
                ,
                "Donec"
                ,
                "lacinia,"
                ,
                "libero"
                ,
                "a"
                ,
                "tincidunt"
                ,
                "blandit,"
                ,
                "nisl"
                ,
                "neque"
                ,
                "tristique"
                ,
                "erat,"
                ,
                "at"
                ,
                "fermentum"
                ,
                "enim"
                ,
                "lectus"
                ,
                "vel"
                ,
                "risus."
                ,
                "Phasellus"
                ,
                "non"
                ,
                "dui"
                ,
                "nisl."
                ,
                "Donec"
                ,
                "congue"
                ,
                "lacus"
                ,
                "euismod"
                ,
                "sapien"
                ,
                "malesuada,"
                ,
                "id"
                ,
                "facilisis"
                ,
                "lectus"
                ,
                "consequat."
                ,
                "Vestibulum"
                ,
                "gravida"
                ,
                "felis"
                ,
                "ac"
                ,
                "varius"
                ,
                "fermentum."
                ,
                "Sed"
                ,
                "elementum"
                ,
                "viverra"
                ,
                "magna."
                ,
                "Suspendisse"
                ,
                "potenti."
                ,
                "Cras"
                ,
                "sed"
                ,
                "mi"
                ,
                "sed"
                ,
                "velit"
                ,
                "pulvinar"
                ,
                "interdum"
                ,
                "nec"
                ,
                "ac"
                ,
                "lorem."
                ,
                "Vivamus"
                ,
                "ac"
                ,
                "nunc"
                ,
                "et"
                ,
                "ligula"
                ,
                "porttitor"
                ,
                "luctus."
                ,
                "Vivamus"
                ,
                "sed"
                ,
                "fermentum"
                ,
                "quam,"
                ,
                "nec"
                ,
                "scelerisque"
                ,
                "neque."
                ,
                "Vivamus"
                ,
                "ut"
                ,
                "magna"
                ,
                "at"
                ,
                "nibh"
                ,
                "pharetra"
                ,
                "elementum"
                ,
                "vel"
                ,
                "a"
                ,
                "sapien."
                ,
                "Sed"
                ,
                "tristique"
                ,
                "sed"
                ,
                "nulla"
                ,
                "at"
                ,
                "dictum."
                ,
                "Aenean"
                ,
                "a"
                ,
                "nibh"
                ,
                "at"
                ,
                "velit"
                ,
                "consequat"
                ,
                "accumsan."
                ,
                "Sed"
                ,
                "venenatis"
                ,
                "ipsum"
                ,
                "nec"
                ,
                "nunc"
                ,
                "dictum"
                ,
                "tincidunt."
                ,
                "In"
                ,
                "non"
                ,
                "felis"
                ,
                "nec"
                ,
                "velit"
                ,
                "volutpat"
                ,
                "ultrices."
                ,
                "Vestibulum"
                ,
                "id"
                ,
                "lacus"
                ,
                "augue."
                ,
                "Nulla"
                ,
                "vel"
                ,
                "laoreet"
                ,
                "sapien."
                ,
                "Nulla"
                ,
                "scelerisque"
                ,
                "sed"
                ,
                "nulla"
                ,
                "eget"
                ,
                "blandit."
                ,
                "Ut"
                ,
                "tristique"
                ,
                "nisi"
                ,
                "at"
                ,
                "augue"
                ,
                "tristique"
                ,
                "porttitor."
                ,
                "Nam"
                ,
                "ac"
                ,
                "quam"
                ,
                "eu"
                ,
                "nulla"
                ,
                "ultrices"
                ,
                "ullamcorper."
                ,
                "Sed"
                ,
                "aliquam"
                ,
                "metus"
                ,
                "in"
                ,
                "nibh"
                ,
                "hendrerit"
                ,
                "suscipit."
                ,
                "Curabitur"
                ,
                "fringilla"
                ,
                "est"
                ,
                "non"
                ,
                "nunc"
                ,
                "vestibulum,"
                ,
                "at"
                ,
                "placerat"
                ,
                "risus"
                ,
                "vehicula."
                ,
                "Donec"
                ,
                "nec"
                ,
                "lectus"
                ,
                "lacinia,"
                ,
                "vulputate"
                ,
                "tortor"
                ,
                "vel,"
                ,
                "posuere"
                ,
                "purus."
                ,
                "Pellentesque"
                ,
                "a"
                ,
                "felis"
                ,
                "ut"
                ,
                "nulla"
                ,
                "ultricies"
                ,
                "pretium."
                ,
                "Nam"
                ,
                "ultrices"
                ,
                "arcu"
                ,
                "ac"
                ,
                "tortor"
                ,
                "viverra,"
                ,
                "eget"
                ,
                "fringilla"
                ,
                "mi"
                ,
                "porttitor."
                ,
                "Etiam"
                ,
                "luctus"
                ,
                "quam"
                ,
                "sit"
                ,
                "amet"
                ,
                "purus"
                ,
                "sodales,"
                ,
                "at"
                ,
                "ullamcorper"
                ,
                "erat"
                ,
                "sodales."
                ,
                "Cras"
                ,
                "vel"
                ,
                "facilisis"
                ,
                "nunc,"
                ,
                "ac"
                ,
                "iaculis"
                ,
                "turpis."
                ,
                "Sed"
                ,
                "tincidunt"
                ,
                "lacus"
                ,
                "id"
                ,
                "sem"
                ,
                "pretium,"
                ,
                "nec"
                ,
                "malesuada"
                ,
                "urna"
                ,
                "egestas."
                ,
                "Sed"
                ,
                "finibus"
                ,
                "erat"
                ,
                "non"
                ,
                "metus"
                ,
                "malesuada,"
                ,
                "sed"
                ,
                "tempor"
                ,
                "lacus"
                ,
                "fermentum."
                ,
                "Nullam"
                ,
                "id"
                ,
                "libero"
                ,
                "non"
                ,
                "ante"
                ,
                "posuere"
                ,
                "feugiat."
                ,
                "Sed"
                ,
                "varius"
                ,
                "viverra"
                ,
                "ex,"
                ,
                "et"
                ,
                "tincidunt"
                ,
                "metus."
                ,
                "Maecenas"
                ,
                "egestas"
                ,
                "semper"
                ,
                "nibh,"
                ,
                "sed"
                ,
                "lacinia"
                ,
                "augue"
                ,
                "pretium"
                ,
                "at."
                ,
                "Quisque"
                ,
                "nec"
                ,
                "lacus"
                ,
                "ut"
                ,
                "ante"
                ,
                "laoreet"
                ,
                "tincidunt."
                ,
                "Cras"
                ,
                "a"
                ,
                "quam"
                ,
                "id"
                ,
                "dolor"
                ,
                "pharetra"
                ,
                "scelerisque."
                ,
                "Sed"
                ,
                "dignissim"
                ,
                "orci"
                ,
                "sem,"
                ,
                "vitae"
                ,
                "laoreet"
                ,
                "lorem"
                ,
                "rutrum"
                ,
                "eget."
                ,
                "Sed"
                ,
                "ac"
                ,
                "nunc"
                ,
                "sit"
                ,
                "amet"
                ,
                "dolor"
                ,
                "venenatis"
                ,
                "pretium"
                ,
                "sed"
                ,
                "at"
                ,
                "justo."
                ,
                "Nulla"
                ,
                "sed"
                ,
                "elit"
                ,
                "id"
                ,
                "lectus"
                ,
                "sodales"
                ,
                "dignissim"
                ,
                "vel"
                ,
                "vel"
                ,
                "elit."
                ,
                "Aenean"
                ,
                "pulvinar"
                ,
                "tincidunt"
                ,
                "diam,"
                ,
                "vel"
                ,
                "cursus"
                ,
                "orci"
                ,
                "dapibus"
                ,
                "in."
                ,
                "Maecenas"
                ,
                "sit"
                ,
                "amet"
                ,
                "nisi"
                ,
                "sed"
                ,
                "neque"
                ,
                "vulputate"
                ,
                "finibus."
                ,
                "Suspendisse"
                ,
                "eget"
                ,
                "nisi"
                ,
                "velit."
                ,
                "Nullam"
                ,
                "vitae"
                ,
                "nibh"
                ,
                "sapien."
                ,
                "Sed"
                ,
                "et"
                ,
                "ex"
                ,
                "vitae"
                ,
                "ex"
                ,
                "efficitur"
                ,
                "malesuada."
                ,
                "Etiam"
                ,
                "efficitur"
                ,
                "ex"
                ,
                "eget"
                ,
                "libero"
                ,
                "dictum,"
                ,
                "at"
                ,
                "finibus"
                ,
                "justo"
                ,
                "volutpat."
                ,
                "Proin"
                ,
                "at"
                ,
                "massa"
                ,
                "a"
                ,
                "dolor"
                ,
                "posuere"
                ,
                "malesuada."
                ,
                "Suspendisse"
                ,
                "vitae"
                ,
                "neque"
                ,
                "nec"
                ,
                "nisl"
                ,
                "gravida"
                ,
                "condimentum."
                ,
                "Integer"
                ,
                "feugiat"
                ,
                "nisl"
                ,
                "ac"
                ,
                "dolor"
                ,
                "aliquam,"
                ,
                "eget"
                ,
                "imperdiet"
                ,
                "augue"
                ,
                "pretium."
                ,
                "Sed"
                ,
                "vulputate"
                ,
                "libero"
                ,
                "ac"
                ,
                "urna"
                ,
                "efficitur,"
                ,
                "nec"
                ,
                "tempor"
                ,
                "ligula"
                ,
                "condimentum."
                ,
                "Cras"
                ,
                "vestibulum"
                ,
                "metus"
                ,
                "eu"
                ,
                "velit"
                ,
                "iaculis,"
                ,
                "a"
                ,
                "vulputate"
                ,
                "lacus"
                ,
                "rhoncus."
                ,
                "Maecenas"
                ,
                "porttitor"
                ,
                "ligula"
                ,
                "ac"
                ,
                "ipsum"
                ,
                "faucibus,"
                ,
                "in"
                ,
                "fermentum"
                ,
                "magna"
                ,
                "vulputate."
                ,
                "Vestibulum"
                ,
                "ac"
                ,
                "ullamcorper"
                ,
                "leo."
                ,
                "Ut"
                ,
                "sit"
                ,
                "amet"
                ,
                "felis"
                ,
                "bibendum,"
                ,
                "imperdiet"
                ,
                "ex"
                ,
                "a,"
                ,
                "bibendum"
                ,
                "mauris."
                ,
                "Nullam"
                ,
                "dignissim"
                ,
                "justo"
                ,
                "vel"
                ,
                "purus"
                ,
                "cursus,"
                ,
                "sit"
                ,
                "amet"
                ,
                "scelerisque"
                ,
                "elit"
                ,
                "laoreet."
                ,
                "Maecenas"
                ,
                "vel"
                ,
                "ligula"
                ,
                "quis"
                ,
                "lacus"
                ,
                "luctus"
                ,
                "sagittis"
                ,
                "sed"
                ,
                "in"
                ,
                "odio."
                ,
                "Pellentesque"
                ,
                "volutpat"
                ,
                "neque"
                ,
                "et"
                ,
                "quam"
                ,
                "tempor,"
                ,
                "eget"
                ,
                "malesuada"
                ,
                "sapien"
                ,
                "finibus."
                ,
                "Curabitur"
                ,
                "malesuada"
                ,
                "nisl"
                ,
                "id"
                ,
                "sem"
                ,
                "imperdiet"
                ,
                "dignissim."
                ,
                "Cras"
                ,
                "venenatis"
                ,
                "augue"
                ,
                "id"
                ,
                "elit"
                ,
                "dictum,"
                ,
                "nec"
                ,
                "ornare"
                ,
                "augue"
                ,
                "viverra."
                ,
                "Donec"
                ,
                "sollicitudin"
                ,
                "viverra"
                ,
                "orci,"
                ,
                "vitae"
                ,
                "laoreet"
                ,
                "neque"
                ,
                "aliquam"
                ,
                "vitae."
                ,
                "Sed"
                ,
                "condimentum"
                ,
                "tellus"
                ,
                "vel"
                ,
                "massa"
                ,
                "dictum"
                ,
                "egestas."
                ,
                "Nullam"
                ,
                "pharetra"
                ,
                "facilisis"
                ,
                "lectus,"
                ,
                "nec"
                ,
                "fringilla"
                ,
                "tortor"
                ,
                "aliquet"
                ,
                "id."
                ,
                "Integer"
                ,
                "ullamcorper"
                ,
                "risus"
                ,
                "at"
                ,
                "nisl"
                ,
                "scelerisque,"
                ,
                "ut"
                ,
                "facilisis"
                ,
                "nisl"
                ,
                "sodales."
                ,
                "Sed"
                ,
                "ac"
                ,
                "bibendum"
                ,
                "augue,"
                ,
                "id"
                ,
                "pharetra"
                ,
                "odio."
                ,
                "Sed"
                ,
                "interdum"
                ,
                "fermentum"
                ,
                "magna,"
                ,
                "nec"
                ,
                "volutpat"
                ,
                "sapien"
                ,
                "fringilla"
                ,
                "at."
                ,
                "Vivamus"
                ,
                "consectetur"
                ,
                "magna"
                ,
                "et"
                ,
                "erat"
                ,
                "malesuada,"
                ,
                "nec"
                ,
                "sagittis"
                ,
                "risus"
                ,
                "fringilla."
                ,
                "Sed"
                ,
                "nec"
                ,
                "risus"
                ,
                "sem."
                ,
                "Phasellus"
                ,
                "quis"
                ,
                "feugiat"
                ,
                "erat."
                ,
                "Nulla"
                ,
                "facilisi."
                ,
                "Aenean"
                ,
                "at"
                ,
                "orci"
                ,
                "sit"
                ,
                "amet"
                ,
                "nunc"
                ,
                "accumsan"
                ,
                "interdum."
                ,
                "Vivamus"
                ,
                "volutpat"
                ,
                "risus"
                ,
                "quis"
                ,
                "dignissim"
                ,
                "pretium."
                ,
                "Aenean"
                ,
                "vulputate,"
                ,
                "enim"
                ,
                "non"
                ,
                "commodo"
                ,
                "lacinia,"
                ,
                "erat"
                ,
                "sapien"
                ,
                "laoreet"
                ,
                "risus,"
                ,
                "at"
                ,
                "efficitur"
                ,
                "sem"
                ,
                "est"
                ,
                "nec"
                ,
                "lectus."
                ,
                "Suspendisse"
                ,
                "porta"
                ,
                "orci"
                ,
                "eget"
                ,
                "lectus"
                ,
                "malesuada,"
                ,
                "vitae"
                ,
                "fringilla"
                ,
                "enim"
                ,
                "ornare."};
        // Test
        Arrays.stream(veryLong).parallel().forEach(System.out::println);
    }
}